baseURL = "http://example.org/"
languageCode = "id"
title = "VOXELATE"
theme = "voxelate_theme"

[params]
  theme_color = "#66ccff"
  color_palette = "blue"
  background_image_url = "images/bgimgCO.png"
  referrer_policy = "same-origin"
  google_fonts = "Oswald|Raleway"
